//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.01.12 at 02:10:53 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://in28minutes.udemy.com/courses", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.udemy.in28minutes.courses;
